<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%><%@ include file="/WEB-INF/views/cmm/include/taglibs.jsp" %>
<script type="text/javascript">var SSOCheckAjaxFunc = {	ajaxLoginCheck : function(){		$.ajax({ 	        url: "<spring:eval expression="@properties['system.sso.domain']" />/sso/sessionkeycheck.jsp",	        dataType : "jsonp",	        jsonp:"callback",	        success: function(data){                                  var loginYn;                 <c:if test="${empty sessionScope.USER_MEMBER_SESSION_INFO}">                                      loginYn = "N";                 </c:if>                 <c:if test="${!empty sessionScope.USER_MEMBER_SESSION_INFO}">                                      loginYn = "Y";                 </c:if>                                  if(loginYn == "N" && data.result != ""){ <%-- 로그인 되어있지 않고 SSO에 로그인 정보가 있을 경우 >  로그인 진행 --%>                     $("#ssoForm").attr("action","${pageContext.request.contextPath}/sso/login.sso");                                     	 $("#sessionkey").val(data.result);                     $("#ssoForm").submit();                                      }else if(loginYn == "Y" && data.result == ""){ <%-- 로그인 되어있고 SSO에 로그인 정보가 없을 경우 >  로그아웃 진행 --%>                     $("#ssoForm").attr("action","${pageContext.request.contextPath}/login/logout");                     $("#ssoForm").submit();                 }else if(data.result != "" && loginYn == "Y" && data.result != "${sessionScope.USER_MEMBER_SESSION_INFO.sessionKey}"){ <%-- 로그인 되어있고 SSO에 로그인 정보가 있으나 둘의 정보가 다를 경우  > SSO정보로 재 로그인 진행 --%>                     $("#sessionkey").val(data.result);                     $("#ssoForm").attr("action","${pageContext.request.contextPath}/sso/login.sso");                                          $("#ssoForm").submit();                 }	            return;	        },	        error: function(){	            return;	        }		});	}}
$(document).ready(function(){	//로그인 체크.	SSOCheckAjaxFunc.ajaxLoginCheck();
});
</script>
<form id="ssoForm" name="ssoForm" method="post" action="">
    <input type="hidden" id="sessionkey" name="sessionkey" value="" />
    <input type="hidden" id="blogin" name="blogin" value="Y" />
    <input type="hidden" id="errortype" name="errortype" value="1" />
</form>